version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: image_engine
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://neondb_owner:npg_9r5bWtxZAjCH@ep-cold-hall-ayauojl4-pooler.c-5.us-east-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require
      GEMINI_API_KEY: ${GEMINI_API_KEY}
    depends_on:
      - db

volumes:
  pgdata: